### ISSUE TITLE
Question/Info: Get ID from extra

### ISSUE THREAD

**Issue by nucle** [Nimrodda/dagger-androidinjector#2]
I think we can change this:
```
@Provides @Named("someId") static String provideSomeId(FeatureActivity featureActivity) {
        return featureActivity.someId;
}
```

to this:

```
@Provides @Named("someId") static String provideSomeId(FeatureActivity featureActivity) {
        return featureActivity.getIntent().getStringExtra(EXTRA_SOME_ID);
}
```

So we don't need to save someID in the activity. What do you think?

**Comment by chrisjenx** [comment]
@nucle correct, should be able to remove reference to `someId` from the `Activity`. As `Activity` is avaliable in your module you can `@Provide` what you need from your `Bundle`

**Comment by mussa-ibragimov** [comment]
How do we convert this class to Kotlin?

**Comment by Nimrodda** [comment]
@nucle 
>So we don't need to save someID in the activity. What do you think?

Yes that's correct. The sample is pretty old. I'll update it.

@mussa-ibragimov 
>How do we convert this class to Kotlin?

I normally don't write Dagger modules with Kotlin, specifically modules that have `static` provide methods. The reason is that Kotlin doesn't support `static` directly in class. We have to use Companion objects which means there's an extra class generated as a singleton + an extra Dagger module generated.
